name: cloud-radar
channels:
  - conda-forge
dependencies:
  - aiobotocore=0.10.0
  - aiohttp=3.9.3
  - aiosignal=1.3.1
  - arm_pyart=1.18.0
  - attrs=23.2.0
  - aws-c-auth=0.7.16
  - aws-c-cal=0.6.10
  - aws-c-common=0.9.14
  - aws-c-compression=0.2.18
  - aws-c-event-stream=0.4.2
  - aws-c-http=0.8.1
  - aws-c-io=0.14.6
  - aws-c-mqtt=0.10.3
  - aws-c-s3=0.5.3
  - aws-c-sdkutils=0.1.15
  - aws-checksums=0.1.18
  - aws-crt-cpp=0.26.4
  - aws-sdk-cpp=1.11.267
  - blosc=1.21.5
  - bokeh=3.4.0
  - botocore=1.10.58
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.27.0
  - ca-certificates=2024.2.2
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cartopy=0.22.0
  - certifi=2024.2.2
  - cftime=1.6.3
  - charset-normalizer=3.3.2
  - click=8.1.7
  - cloudpickle=3.0.0
  - cmweather=0.3.2
  - contourpy=1.2.0
  - cycler=0.12.1
  - cytoolz=0.12.3
  - dask=2023.4.0
  - dask-core=2023.4.0
  - distributed=2023.4.0
  - docutils=0.20.1
  - eccodes=2.34.1
  - fonttools=4.50.0
  - freetype=2.12.1
  - frozenlist=1.4.1
  - fsspec=2021.7.0
  - geos=3.12.1
  - gflags=2.2.2
  - glog=0.7.0
  - h5netcdf=1.3.0
  - h5py=3.10.0
  - hdf4=4.2.15
  - hdf5=1.14.3
  - icu=73.2
  - idna=3.6
  - importlib-metadata=7.1.0
  - importlib_metadata=7.1.0
  - jasper=4.2.2
  - jinja2=3.1.3
  - jmespath=0.10.0
  - kiwisolver=1.4.5
  - krb5=1.21.2
  - lat_lon_parser=1.3.0
  - lcms2=2.16
  - lerc=4.0.0
  - libabseil=20240116.1
  - libaec=1.1.3
  - libarrow=15.0.2
  - libarrow-acero=15.0.2
  - libarrow-dataset=15.0.2
  - libarrow-flight=15.0.2
  - libarrow-flight-sql=15.0.2
  - libarrow-gandiva=15.0.2
  - libarrow-substrait=15.0.2
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcrc32c=1.1.2
  - libcurl=8.6.0
  - libcxx=16.0.6
  - libdeflate=1.19
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.6.2
  - libffi=3.4.2
  - libgfortran5=13.2.0
  - libgoogle-cloud=2.22.0
  - libgoogle-cloud-storage=2.22.0
  - libgrpc=1.62.1
  - libiconv=1.17
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - libllvm14=14.0.6
  - libllvm16=16.0.6
  - libnetcdf=4.9.2
  - libnghttp2=1.58.0
  - libopenblas=0.3.26
  - libparquet=15.0.2
  - libpng=1.6.43
  - libprotobuf=4.25.3
  - libre2-11=2023.09.01
  - libsqlite=3.45.2
  - libssh2=1.11.0
  - libthrift=0.19.0
  - libtiff=4.6.0
  - libutf8proc=2.8.0
  - libwebp-base=1.3.2
  - libxcb=1.15
  - libxml2=2.12.6
  - libzip=1.10.1
  - libzlib=1.2.13
  - llvm-openmp=18.1.2
  - llvmlite=0.42.0
  - locket=1.0.0
  - lz4=4.3.3
  - lz4-c=1.9.4
  - markupsafe=2.1.5
  - matplotlib=3.8.3
  - matplotlib-base=3.8.3
  - mda-xdrlib=0.2.0
  - metpy=1.6.1
  - msgpack-python=1.0.7
  - multidict=6.0.5
  - munkres=1.1.4
  - ncurses=6.4.20240210
  - netcdf4=1.6.5
  - numba=0.59.0
  - numpy=1.26.4
  - open-radar-data=0.1.0
  - openjpeg=2.5.2
  - openssl=3.2.1
  - orc=2.0.0
  - packaging=24.0
  - pandas=2.2.1
  - partd=1.4.1
  - pillow=10.2.0
  - pint=0.23
  - pip=24.0
  - platformdirs=4.2.0
  - pooch=1.8.1
  - proj=9.3.1
  - psutil=5.9.8
  - pthread-stubs=0.4
  - pyarrow=15.0.2
  - pygrib=2.1.5
  - pyparsing=3.1.2
  - pyproj=3.6.1
  - pyshp=2.3.1
  - pysocks=1.7.1
  - python=3.12.2
  - python-dateutil=2.9.0
  - python-tzdata=2024.1
  - python_abi=3.12
  - pytz=2024.1
  - pyyaml=6.0.1
  - re2=2023.09.01
  - readline=8.2
  - requests=2.31.0
  - s3fs=2021.7.0
  - scipy=1.12.0
  - setuptools=69.2.0
  - setuptools-scm=8.0.4
  - setuptools_scm=8.0.4
  - shapely=2.0.3
  - six=1.16.0
  - snappy=1.1.10
  - sortedcontainers=2.4.0
  - sqlite=3.45.2
  - tblib=3.0.0
  - timeout-decorator=0.5.0
  - tk=8.6.13
  - tomli=2.0.1
  - toolz=0.12.1
  - tornado=6.4
  - traitlets=5.14.2
  - typing-extensions=4.10.0
  - typing_extensions=4.10.0
  - tzdata=2024a
  - urllib3=2.2.1
  - versioneer=0.29
  - wheel=0.43.0
  - wrapt=1.16.0
  - xarray=2024.2.0
  - xarray-datatree=0.0.14
  - xmltodict=0.13.0
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xradar=0.4.3
  - xyzservices=2023.10.1
  - xz=5.2.6
  - yaml=0.2.5
  - yarl=1.9.4
  - zict=3.0.0
  - zipp=3.17.0
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - geojson==3.1.0
      - geojsoncontour==0.4.0
